<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script>
    new Promise((resolve,reject)=> {
        resolve(1);
        //reject(2);//只会输出上面的1
        resolve(3);//只会输出上面的1
    }).then(e=>{
        console.log(e)
    },m=>{
        console.log(m)
    })

    Promise.resolve().then(() => {
        console.log('ok1')
        throw 'throw error1'
    }).then(() => {
        console.log('ok2')
    }, err => {//若没有传入该回调，则会直接跳到最后一步
        // 捕获错误
        console.log('er1r->', err)
    }).then(() => {
        // 该函数将被调用
        console.log('ok3')
        throw 'throw error3'
    }).then(() => {
        // 错误捕获前的函数不会被调用
        console.log('ok4')
    }).catch(err => {
        console.log('err3->', err)
    })


</script>
</body>
</html>